version: 2
dependencies:
  cache_directories:
    - "vendor/apt"
    - "vendor/apt/archives"
jobs:
  build:
    docker:
      - image: neomatrix369/graalvm-suite-jdk8
    steps:
      - checkout
      - restore_cache:
          keys:
            - os-deps-{{ arch }}-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
            - os-deps-{{ arch }}-{{ .Branch }}
      - run:
          name: Define Environment Variables and update JAVA_HOME and PATH at Runtime
          command: |
            echo 'Even though we are using tag jdk8u152-b16, the location where JAVA_HOME is, is named jdk8u144-b01'
            echo 'This is being fixed in subsequent versions of the JDK'
            echo 'export JAVA_VERSION=jdk8u144-b01'                               >> ${BASH_ENV}
            echo 'export JAVA_HOME=/opt/java/openjdk/${JAVA_VERSION}'             >> ${BASH_ENV}
            echo 'export PATH=${JAVA_HOME}/bin:${PATH}'                           >> ${BASH_ENV}
            echo 'export BASEDIR=${PWD}'                                          >> ${BASH_ENV}
            echo 'export SCRIPTS_LIB_DIR=${BASEDIR}/build/x86_64/linux_macos/lib' >> ${BASH_ENV}
            echo 'export MX=${BASEDIR}/mx/mx'                                     >> ${BASH_ENV}
            echo 'export JDK_GRAAL_FOLDER_NAME=jdk8-with-graal'                   >> ${BASH_ENV}
            echo 'export GRAAL_JVMCI_8_TAG=master'                                >> ${BASH_ENV}
            echo 'export BUILD_ARTIFACTS_DIR=${BASEDIR}/${JDK_GRAAL_FOLDER_NAME}' >> ${BASH_ENV}
            echo 'export RUN_TESTS="true"'                                        >> ${BASH_ENV}
            echo 'export HOTSPOT_BUILD_JOBS=2'                                    >> ${BASH_ENV}
            source ${BASH_ENV}
      - run:
          name: Display HW, SW, Runtime env. info and versions of dependencies
          command: ./build/x86_64/linux_macos/lib/displayDependencyVersion.sh
      - run:
          name: Setup MX
          command: ./build/x86_64/linux_macos/lib/setupMX.sh ${BASEDIR}
      - run:
          name: Build JDK JVMCI
          command: ./build/x86_64/linux_macos/lib/build_JDK_JVMCI.sh ${BASEDIR} ${MX}
          timeout: 20m
          no_output_timeout: 15m
      - run:
          name: Run JDK JVMCI Tests
          command: ./build/x86_64/linux_macos/lib/run_JDK_JVMCI_Tests.sh ${BASEDIR} ${MX}
      - run:
          name: Setting up environment and Build Graal Compiler
          command: |
            echo ">>>> Currently JAVA_HOME=${JAVA_HOME}"
            JDK8_JVMCI_HOME="$(cd ${BASEDIR}/graal-jvmci-8/ && ${MX} --java-home ${JAVA_HOME} jdkhome)"
            echo "export JVMCI_VERSION_CHECK='ignore'" >> ${BASH_ENV}
            echo "export JAVA_HOME=${JDK8_JVMCI_HOME}" >> ${BASH_ENV}
            source ${BASH_ENV}
      - run:
          name: Build the Graal Compiler and embed it into the JDK (JDK8 with JVMCI enabled)
          command: |
            echo ">>>> Using JDK8_JVMCI_HOME as JAVA_HOME (${JAVA_HOME})"
            ./build/x86_64/linux_macos/lib/buildGraalCompiler.sh ${BASEDIR} ${MX} ${BUILD_ARTIFACTS_DIR}
          timeout: 10m
          no_output_timeout: 7m
      - run:
          name: Sanity check artifacts
          command: |
            ./build/x86_64/linux_macos/lib/sanityCheckArtifacts.sh ${BASEDIR} ${JDK_GRAAL_FOLDER_NAME}
          timeout: 3m
          no_output_timeout: 2m
      - run:
          name: Archiving artifacts
          command: |
            ./build/x86_64/linux_macos/lib/archivingArtifacts.sh ${BASEDIR} ${MX} ${JDK_GRAAL_FOLDER_NAME} ${BUILD_ARTIFACTS_DIR}
          timeout: 3m
          no_output_timeout: 2m
      - store_artifacts:
          path: jdk8-with-graal-local/
